language: php
dist: trusty
sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - nightly
  - 8.1
  - 8.0
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0

matrix:
  fast_finish: true
  include:
    - name: Coding standards
      php: 7.3
      env: CODING_STANDARDS=1

before_install:
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - composer install --no-interaction --prefer-dist

script:
  - |
    if [[ ${CODING_STANDARDS} ]]; then
      ./vendor/bin/php-cs-fixer fix --dry-run
    else
      vendor/bin/phpunit
    fi

notifications:
  email: false
